### ISSUE TITLE
how to make the background of image button to be transparent?

### ISSUE THREAD

**Issue by anghd** [littlevgl/lv_lib_lodepng#32]
### I'm using LVGL8.0 and RGB585 format images , 
 I tried #define LV_COLOR_CHROMA_KEY lv_color_hex(0x000000) /*black as background and not draw*/ and it takes no effect.
my main screen's background is black and there're some overlapped area between image buttons as bellow ing:

**Comment by kisvegabor** [comment]
Just add alpha channel to the image using GIMP or Photoshop.

---

We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.

**Comment by anghd** [comment]
thank you.
