### ISSUE TITLE
Does APNG support?

### ISSUE THREAD

**Issue by guoweilkd** [littlevgl/lv_lib_lodepng#8]

**Comment by embeddedt** [comment]
I don't think lodepng (the underlying decoder being used) supports APNG. If you want animations I would suggest looking into https://github.com/lvgl/lv_lib_gif.

**Comment by embeddedt** [comment]
It looks like APNG is an extension of PNG, so the first frame will probably display fine. However, there is no mechanism I know of to get lodepng to display the next frame.

**Comment by guoweilkd** [comment]
I use libpng+apng patch to implement APNG in LVGL. https://github.com/guoweilkd/lv_lib_apng
How to add it to lvgl Repo.

**Comment by kisvegabor** [comment]
Happy to hear that you could make it work!

In this repo are using `lodepng` as png lib but it seems you are using a different one. 

Could you send a PR with the changes? We can merge it into a new branch and if it's better than the current `lodepng` lib we can replace it with yours.
